[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "django-mongodb-extensions"
version = "0.1.0"
description = "PyMongo support for Flask applications"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.10"
